{
  "name": "plainerror",
  "description": "Easy to got error from async promise flow",
  "main": "lib/index.js",
  "module": "src/index.ts",
  "version": "1.0.4",
  "scripts": {
    "build": "tsc -w"
  },
  "files": [
    "lib",
    "src"
  ],
  "keywords": [
    "promise",
    "promise error",
    "catch",
    "async"
  ],
  "bugs": {
    "url": "https://github.com/189/plainerror/issues"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/189/plainerror"
  },
  "license": "MIT",
  "author": "189<kv.wang87@gmail.com>",
  "dependencies": {
    "tslint": "^6.0.0",
    "typescript": "^3.8.2"
  },
  "homepage": "https://github.com/189/plainerror",
  "typings": "lib/index.d.ts"
}
